- name: Install kubernetes on controller node (ubuntu)
  hosts: localhost
  connection: local
  gather_facts: false
  become: yes
  vars:
    user: ubuntu 

  tasks:

  - name: Set timezone to Europe/Lisbon
    ansible.builtin.timezone:
      name: Europe/Lisbon

  - name: Update and Upgrade Ubuntu
    apt:
      upgrade: dist
      force_apt_get: yes
      update_cache: yes
      autoremove: yes
      cache_valid_time: "432000"

  - name: Install common ssh_key
    ansible.builtin.authorized_key:
      user: "{{ user }}"
      state: present
      key: "{{ lookup('file', 'id_rsa.pub') }}"

  - name: Copy ssh private and public key
    ansible.builtin.copy:
      src: "{{ item }}"
      dest: /home/{{ user }}/.ssh/
      owner: "{{ user }}"
      group: "{{ user }}"
      mode: '0600'
    with_items:
    - id_rsa
    - id_rsa.pub
  